apiVersion: v1
kind: Service
metadata: 
   name: mysql-users
   namespace: sockshop
spec:
   selector:
     app: mysql-users
   ports:
   - port: 3306
     targetPort: 3306
   type: ClusterIP